name: SlackTest

on:
    schedule:
      - cron: "*/1 * * * *"
    push:
        branches:
            - main

jobs:
  send_to_slack:
    runs-on: ubuntu-latest

    steps:
      - name: GetSecurityInfo
        id: security-advisories
        run: |
          advisories=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/security/advisories?state=draft")
          echo "::set-output name=advisories::$advisories"

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'securitytesting'
          payload: |
            {
              "text": "GitHub Action build result: ${{ steps.security-advisories.outputs.advisories }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ steps.security-advisories.outputs.advisories }}"
                  }
                }
              ]
            }

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
