name: SlackTest

on:
  push:
    branches:
      - master

jobs:
  send_to_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'your_slack_channel_here'
          slack-message: "GitHub build result: ${{ job.status }}"

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
